# vim:ft=ruby

vm_ram = 2048
vm_cpus = 2

Vagrant.configure("2") do |config|
  config.vm.box = "senglin/win-10-enterprise-vs2015community"
  config.vm.box_check_update = false

  config.vm.provider :virtualbox do |v, override|
    v.customize ["modifyvm", :id,
                 "--memory", vm_ram,
                 "--cpus", vm_cpus,
                 "--natdnshostresolver1", "on",
                 "--natdnsproxy1", "on"]
  end

  config.vm.define :seafile_dev_win10 do |cfg|
    cfg.vm.hostname = "seafile-dev-win"
    cfg.vm.network :private_network, ip: "172.16.90.105", type: "static"
  end
end
