# vim:ft=ruby

vm_gui = ENV.fetch("SEAFILE_GUI", false)
vm_ram = ENV.fetch("SEAFILE_DEV_VM_RAM", 2048).to_i

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.synced_folder '~/.aptcache/trusty64', '/var/cache/apt/archives', :create => true

  config.vm.provision :shell, :path => "../base-provision.sh"
  config.vm.provision :shell, :path => 'provision.sh'
  config.vm.provision :shell, :path => 'build.sh'
  config.vm.provision :shell, :path => 'server.sh', :args => 'init'

  config.vm.provider :vmware_fusion do |v, override|
    override.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vmwarefusion.box"
    v.gui = vm_gui
    v.vmx["memsize"] = vm_ram.to_s
    v.vmx["numvcpus"] = "2"
  end

  config.vm.provider :virtualbox do |v, override|
    override.vm.box_url = "http://files.vagrantup.com/precise64.box"
    v.gui = vm_gui
    v.customize ["modifyvm", :id,
                 "--memory", vm_ram,
                 "--cpus", 2,
                 "--natdnshostresolver1", "on",
                 "--natdnsproxy1", "on"]
  end

  config.vm.define :seafile_dev do |cfg|
    cfg.vm.hostname = "seafile-dev"
    cfg.vm.hostname = "seafile-dev"
    cfg.vm.network :private_network, ip: "172.16.90.100", type: "static"
  end
end
