# vim:ft=ruby

vm_gui = ENV.fetch("SEAFILE_GUI", false)
vm_ram = ENV.fetch("SEAFILE_DEV_VM_RAM", 1024).to_i
vm_cpus = ENV.fetch("SEAFILE_DEV_VM_CPUS", 2).to_i

Vagrant.configure("2") do |config|
  config.vm.box = "boxcutter/ubuntu1604-desktop"
  config.vm.box_check_update = false
  # Removes annoying message about public key replacement
  config.ssh.insert_key = false
  config.vm.synced_folder "~/.aptcache/xenial64", "/var/cache/apt/archives", :create => true, mount_options: ["dmode=777,fmode=666"]

  config.vm.provision :shell, :path => 'provision.sh'

  config.vm.provider :virtualbox do |v, override|
    v.gui = vm_gui
    v.customize ["modifyvm", :id,
                 "--memory", vm_ram,
                 "--cpus", vm_cpus,
                 "--natdnshostresolver1", "on",
                 "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--accelerate3d", "off"]
  end

  config.vm.define :ubuntu1604 do |cfg|
    cfg.vm.hostname = "ubuntu1604"
    cfg.vm.hostname = "ubuntu1604"
    cfg.vm.network :private_network, ip: "172.16.90.107", type: "static"
  end
end
